cxx_binary(
  name = 'hello',
  srcs = [
    'hello.cc',
  ],
  deps = [
    '//src/lib:lib'
  ],
),

cxx_test(
  name = 'lib_test',
  srcs = [
    'test.cc',
  ],
  deps = [
    '//src/lib:lib',
    '//src/gtest:gtest',
  ],
)